### ISSUE TITLE
Modal Apex Controller Issue

### ISSUE THREAD

**Issue by yinama** [revaturelabs/ProjectForce#15]
## Known Issues:<br/>
+ getTrainer at line 162, getRoom at line 338 and getProject at line 508 currently not working
+ getProject method at line 508 was working properly, but was commented out due to the other two not working
+ For getRoom method, the `secondFilterRoomList` at line 353 filters out all the rooms, leaving an index out of bound error later on.  This filter should only filter out trainings that started before the start date parameter passed in
+ getTrainer at line 162 is expected to work, works in testing and anonymous window, need to write JS code to call this method

**Comment by mruizrevature** [comment]
Modal has changed.
