### ISSUE TITLE
Fonts are not consistent

### ISSUE THREAD

**Issue by Zpecterr** [revaturelabs/ProjectForce#17]
Since futura font isn't native to salesforce, the font family had to be included as a static resource. From there, we used a ltng:require tag in the component to include it, and a @font-family tag in the css to include it. Right now, when inspected, each element says it's using futura, but that is only true on the elements that aren't using lightning design system.

**Comment by mruizrevature** [comment]
Still active. Please use [Revature Branding Guidelines](https://github.com/revaturelabs/ProjectForce/blob/091619salesforce/RevatureFontAndColors.pdf)

**Comment by learnbenlearn** [comment]
Sabir fixed this, futura font is now used throughout the project force page
